server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/schnjov/config-service
          search-paths: src/main/resources/config-data
  application:
    name: config-service
management:
  endpoints:
    web:
      exposure:
        include: "*"
