server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: https://${EUREKA:localhost}:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: proveedor-service
          uri: localhost:8085
          predicates:
            - Path=/proveedor-service/**
        - id: acopio-service
          uri:
          predicates:
            - Path=/acopio-service/**
        - id: valores-service
          uri: lb://valores-service
          predicates:
            - Path=/valores-service/**
        - id: planilla-service
          uri: lb://planilla-service
          predicates:
            - Path=/planilla-service/**